apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 4369
    protocol: TCP
    name: tcp-4369
  - port: 5671
    protocol: TCP
    name: tcp-5671
  - port: 5672
    protocol: TCP
    name: tcp-5672
  - port: 25672
    protocol: TCP
    name: tcp-25672
  - port: 15672
    protocol: TCP
    name: tcp-15672
  - port: 61613
    protocol: TCP
    name: tcp-61613
  - port: 61614
    protocol: TCP
    name: tcp-61614
  selector:
    app: rabbitmq
