apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: "rabbitmq"
          image: 'ikoenig/rabbitmq-stomp-management:latest'
          env:
          - name: "RABBITMQ_ERLANG_COOKIE"
            value: "95f50708-7b6f-424e-810e-d0373a95ed20"
          - name: "RABBITMQ_DEFAULT_USER"
            value: "admin"
          - name: "RABBITMQ_DEFAULT_PASS"
            value: "abc123"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
          volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-data
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
